// ============================================
// Camp 8 — College Coaches Directory
// File: coaches-data.js
//
// HOW TO UPDATE:
// 1. Find the program by school name
// 2. Update the coach fields
// 3. Update "lastUpdated" to today's date
// 4. Save and push to GitHub
//
// DIVISIONS: FBS, FCS, D2, D3, JUCO
// ============================================

const COACHES_DATA = [

  // ============================================
  // FBS — SEC
  // ============================================
  {
    school: 'University of Georgia',
    domain: 'uga.edu',
    nickname: 'Bulldogs',
    division: 'FBS',
    conference: 'SEC',
    state: 'GA',
    city: 'Athens',
    headCoach: 'Kirby Smart',
    oc: 'Mike Bobo',
    dc: 'Glenn Schumann',
    recruitingCoord: 'Bryan McClendon',
    staffPage: 'https://georgiadogs.com/sports/football/roster/coaches',
        contactEmail: 'ahunt@sports.uga.edu',
    contactPhone: '(706) 542-7915',
    mailingAddress: 'UGA Athletics/Football, P.O. Box 1472, Athens, GA 30603',
    lastUpdated: '2026-04',
    hcTwitter: 'KirbySmartUGA',
    hcInstagram: 'kirbysmart',
    rcTwitter: 'CoachMcClendon',
    rcInstagram: 'coachmcclendon',
    espnId: 61,
  },
  {
    school: 'University of Alabama',
    domain: 'ua.edu',
    nickname: 'Crimson Tide',
    division: 'FBS',
    conference: 'SEC',
    state: 'AL',
    city: 'Tuscaloosa',
    headCoach: 'Kalen DeBoer',
    oc: 'Nick Sheridan',
    dc: 'Kane Wommack',
    recruitingCoord: 'JaMarcus Shephard',
    staffPage: 'https://rolltide.com/sports/football/roster/coaches',
        contactEmail: 'fgaston@ia.ua.edu',
    contactPhone: '(205) 348-3600',
    mailingAddress: 'UA Football, Box 870323, Tuscaloosa, AL 35487',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachDeBoer',
    hcInstagram: 'coachdeboer',
    rcTwitter: 'CoachJShephard',
    rcInstagram: '',
    espnId: 333,
  },
  {
    school: 'University of Florida',
    domain: 'ufl.edu',
    nickname: 'Gators',
    division: 'FBS',
    conference: 'SEC',
    state: 'FL',
    city: 'Gainesville',
    headCoach: 'Billy Napier',
    oc: 'Bobby Petrino',
    dc: 'Austin Armstrong',
    recruitingCoord: 'Corey Raymond',
    staffPage: 'https://floridagators.com/sports/football/roster/coaches',
        contactEmail: 'sams@gators.ufl.edu',
    contactPhone: '(352) 375-4683',
    mailingAddress: 'UAA Football, P.O. Box 14485, Gainesville, FL 32604',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachBillyNapier',
    hcInstagram: 'coachbillynapier',
    rcTwitter: 'CoachCRaymond',
    rcInstagram: '',
    espnId: 57,
  },
  {
    school: 'University of Tennessee',
    domain: 'utk.edu',
    nickname: 'Volunteers',
    division: 'FBS',
    conference: 'SEC',
    state: 'TN',
    city: 'Knoxville',
    headCoach: 'Josh Heupel',
    oc: 'Joey Halzle',
    dc: 'Tim Banks',
    recruitingCoord: 'Tee Martin',
    staffPage: 'https://utsports.com/sports/football/roster/coaches',
        contactEmail: 'utad@utk.edu',
    contactPhone: '(865) 974-1234',
    mailingAddress: 'UT Football, P.O. Box 15162, Knoxville, TN 37901',
    lastUpdated: '2026-04',
    hcTwitter: 'HeupelJosh',
    hcInstagram: 'heupeljosh',
    rcTwitter: 'TeeMartin8',
    rcInstagram: 'teemartin8',
    espnId: 2633,
  },
  {
    school: 'LSU',
    domain: 'lsu.edu',
    nickname: 'Tigers',
    division: 'FBS',
    conference: 'SEC',
    state: 'LA',
    city: 'Baton Rouge',
    headCoach: 'Brian Kelly',
    oc: 'Joe Sloan',
    dc: 'Blake Baker',
    recruitingCoord: 'Robert Steeples',
    staffPage: 'https://lsusports.net/sports/football/roster/coaches',
        contactEmail: 'football@lsu.edu',
    contactPhone: '(225) 578-8001',
    mailingAddress: 'LSU Athletics/Football, P.O. Box 2509, Baton Rouge, LA 70894',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachBrianKelly',
    hcInstagram: 'coachbriankelly',
    rcTwitter: 'CoachSteeples',
    rcInstagram: '',
    espnId: 99,
  },
  {
    school: 'University of Texas',
    domain: 'utexas.edu',
    nickname: 'Longhorns',
    division: 'FBS',
    conference: 'SEC',
    state: 'TX',
    city: 'Austin',
    headCoach: 'Steve Sarkisian',
    oc: 'Kyle Flood',
    dc: 'Pete Kwiatkowski',
    recruitingCoord: 'Jeff Banks',
    staffPage: 'https://texassports.com/sports/football/roster/coaches',
        contactEmail: 'kasey.johnson@athletics.utexas.edu',
    contactPhone: '(512) 471-3050',
    mailingAddress: 'UT Athletic Dept, Austin, TX 78713',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachSark',
    hcInstagram: 'coachsark',
    rcTwitter: 'CoachJeffBanks',
    rcInstagram: '',
    espnId: 251,
  },
  {
    school: 'Texas A&M University',
    domain: 'tamu.edu',
    nickname: 'Aggies',
    division: 'FBS',
    conference: 'SEC',
    state: 'TX',
    city: 'College Station',
    headCoach: 'Mike Elko',
    oc: 'Collin Klein',
    dc: 'Jay Bateman',
    recruitingCoord: 'Terry Price',
    staffPage: 'https://12thman.com/sports/football/roster/coaches',
        contactEmail: 'recruiting-fb@athletics.tamu.edu',
    contactPhone: '(979) 845-3500',
    mailingAddress: 'TAMU Football Office, P.O. Box 30017, College Station, TX 77843',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachMikeElko',
    hcInstagram: '',
    rcTwitter: 'CoachTerryPrice',
    rcInstagram: '',
    espnId: 245,
  },
  {
    school: 'University of Mississippi',
    domain: 'olemiss.edu',
    nickname: 'Rebels',
    division: 'FBS',
    conference: 'SEC',
    state: 'MS',
    city: 'Oxford',
    headCoach: 'Lane Kiffin',
    oc: 'Charlie Weis Jr.',
    dc: 'Pete Golding',
    recruitingCoord: 'Jamar Cain',
    staffPage: 'https://olemisssports.com/sports/football/roster/coaches',
        contactEmail: 'chyna@olemiss.edu',
    contactPhone: '(662) 915-7547',
    mailingAddress: 'Ole Miss Football, 908 All-American Dr, University, MS 38677',
    lastUpdated: '2026-04',
    hcTwitter: 'Lane_Kiffin',
    hcInstagram: 'lanekiffin',
    rcTwitter: 'CoachJamarCain',
    rcInstagram: 'coachjamar',
    espnId: 145,
  },
  {
    school: 'Auburn University',
    domain: 'auburn.edu',
    nickname: 'Tigers',
    division: 'FBS',
    conference: 'SEC',
    state: 'AL',
    city: 'Auburn',
    headCoach: 'Hugh Freeze',
    oc: 'Philip Montgomery',
    dc: 'Ron Roberts',
    recruitingCoord: 'Carnell Williams',
    staffPage: 'https://auburntigers.com/sports/football/roster/coaches',
        contactEmail: 'ezc0011@auburn.edu',
    contactPhone: '(334) 844-9890',
    mailingAddress: 'Auburn Football, 392 South Donahue Dr, Auburn, AL 36849',
    lastUpdated: '2026-04',
    hcTwitter: 'HughFreeze10',
    hcInstagram: 'hughfreeze',
    rcTwitter: 'CarnellWilliams',
    rcInstagram: 'carnellwilliams',
    espnId: 2,
  },
  {
    school: 'University of South Carolina',
    domain: 'sc.edu',
    nickname: 'Gamecocks',
    division: 'FBS',
    conference: 'SEC',
    state: 'SC',
    city: 'Columbia',
    headCoach: 'Shane Beamer',
    oc: 'Dowell Loggains',
    dc: 'Clayton White',
    recruitingCoord: 'Des Kitchings',
    staffPage: 'https://gamecocksonline.com/sports/football/roster/coaches',
        contactEmail: 'shinep@mailbox.sc.edu',
    contactPhone: '(803) 777-4271',
    mailingAddress: 'SC Football, Rex Enright Athletic Ctr, 1300 Rosewood Dr, Columbia, SC 29208',
    lastUpdated: '2026-04',
    hcTwitter: 'ShaneBeamer',
    hcInstagram: 'shanebeamer',
    rcTwitter: 'CoachDesK',
    rcInstagram: '',
    espnId: 2579,
  },
  {
    school: 'Vanderbilt University',
    domain: 'vanderbilt.edu',
    nickname: 'Commodores',
    division: 'FBS',
    conference: 'SEC',
    state: 'TN',
    city: 'Nashville',
    headCoach: 'Clark Lea',
    oc: 'Tim Beck',
    dc: 'Tevita Fifita',
    recruitingCoord: 'Bryan Ellis',
    staffPage: 'https://vucommodores.com/sports/football/roster/coaches',
        contactEmail: 'football_recruiting@vanderbilt.edu',
    contactPhone: '(615) 322-3565',
    mailingAddress: 'Vanderbilt Football, 2601 Jess Neely Dr, Nashville, TN 37212',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachClarkLea',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 238,
  },
  {
    school: 'Mississippi State University',
    domain: 'msstate.edu',
    nickname: 'Bulldogs',
    division: 'FBS',
    conference: 'SEC',
    state: 'MS',
    city: 'Starkville',
    headCoach: 'Jeff Lebby',
    oc: 'Kevin Barbay',
    dc: 'Zach Arnett',
    recruitingCoord: 'Marcus Woodson',
    staffPage: 'https://hailstate.com/sports/football/roster/coaches',
        contactEmail: 'felker@athletics.msstate.edu',
    contactPhone: '(662) 325-2539',
    mailingAddress: 'MSU Football, P.O. Box 5327, Mississippi State, MS 39762',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachLebby',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 344,
  },
  {
    school: 'University of Kentucky',
    domain: 'uky.edu',
    nickname: 'Wildcats',
    division: 'FBS',
    conference: 'SEC',
    state: 'KY',
    city: 'Lexington',
    headCoach: 'Mark Stoops',
    oc: 'Bush Hamdan',
    dc: 'Brad White',
    recruitingCoord: 'Vince Marrow',
    staffPage: 'https://ukathletics.com/sports/football/roster/coaches',
        contactEmail: 'C.snow.iii@uky.edu',
    contactPhone: '(859) 257-3611',
    mailingAddress: 'UK Athletics/Football, 338 Lexington Ave, Lexington, KY 40506',
    lastUpdated: '2026-04',
    hcTwitter: 'UKCoachStoops',
    hcInstagram: '',
    rcTwitter: 'VinceMarrow',
    rcInstagram: 'vincemarrow',
    espnId: 96,
  },
  {
    school: 'University of Missouri',
    domain: 'missouri.edu',
    nickname: 'Tigers',
    division: 'FBS',
    conference: 'SEC',
    state: 'MO',
    city: 'Columbia',
    headCoach: 'Eli Drinkwitz',
    oc: 'Kirby Moore',
    dc: 'Vernon Hargreaves',
    recruitingCoord: 'Marcus Johnson',
    staffPage: 'https://mutigers.com/sports/football/roster/coaches',
        contactEmail: 'hillra@missouri.edu',
    contactPhone: '(573) 882-2404',
    mailingAddress: 'Mizzou Athletics, One Champions Drive, Columbia, MO 65205',
    lastUpdated: '2026-04'
    espnId: 142,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'University of Arkansas',
    domain: 'uark.edu',
    nickname: 'Razorbacks',
    division: 'FBS',
    conference: 'SEC',
    state: 'AR',
    city: 'Fayetteville',
    headCoach: 'Sam Pittman',
    oc: 'Bobby Petrino',
    dc: 'Travis Williams',
    recruitingCoord: 'Marcus Woodson',
    staffPage: 'https://arkansasrazorbacks.com/sports/football/roster/coaches',
        contactEmail: 'rpetrino@uark.edu',
    contactPhone: '(479) 575-4849',
    mailingAddress: 'UA Football, 350 N Razorback Road, Fayetteville, AR 72702',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachSamPittman',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 8,
  },

  // ============================================
  // FBS — ACC
  // ============================================
  {
    school: 'Clemson University',
    domain: 'clemson.edu',
    nickname: 'Tigers',
    division: 'FBS',
    conference: 'ACC',
    state: 'SC',
    city: 'Clemson',
    headCoach: 'Dabo Swinney',
    oc: 'Garrett Riley',
    dc: 'Wes Goodwin',
    recruitingCoord: 'Kyle Richardson',
    staffPage: 'https://clemsontigers.com/sports/football/roster/coaches',
        contactEmail: 'footballrecruiting@clemson.edu',
    contactPhone: '(864) 656-2101',
    mailingAddress: 'Clemson Football, P.O. Box 31, Clemson, SC 29634',
    lastUpdated: '2026-04',
    hcTwitter: 'DaboSwinney',
    hcInstagram: 'daboswinney',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 228,
  },
  {
    school: 'Florida State University',
    domain: 'fsu.edu',
    nickname: 'Seminoles',
    division: 'FBS',
    conference: 'ACC',
    state: 'FL',
    city: 'Tallahassee',
    headCoach: 'Mike Norvell',
    oc: 'Alex Atkins',
    dc: 'Patrick Toney',
    recruitingCoord: 'Jason Leach',
    staffPage: 'https://seminoles.com/sports/football/roster/coaches',
        contactEmail: 'football@fsu.edu',
    contactPhone: '(850) 644-1073',
    mailingAddress: 'FSU Football, P.O. Box 2195, Tallahassee, FL 32316',
    lastUpdated: '2026-04',
    hcTwitter: 'Coach_Norvell',
    hcInstagram: 'coachnorvellfsu',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 52,
  },
  {
    school: 'University of Miami',
    domain: 'miami.edu',
    nickname: 'Hurricanes',
    division: 'FBS',
    conference: 'ACC',
    state: 'FL',
    city: 'Coral Gables',
    headCoach: 'Mario Cristobal',
    oc: 'Shannon Dawson',
    dc: 'Lance Leopold',
    recruitingCoord: 'Gino Guidugli',
    staffPage: 'https://hurricanesports.com/sports/football/roster/coaches',
        contactEmail: 'footballrecruiting@miami.edu',
    contactPhone: '(305) 284-2263',
    mailingAddress: 'UM Football, 6201 San Amaro Drive, Coral Gables, FL 33146',
    lastUpdated: '2026-04',
    hcTwitter: 'Coach_Cristobal',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 2390,
  },
  {
    school: 'Georgia Tech',
    domain: 'gatech.edu',
    nickname: 'Yellow Jackets',
    division: 'FBS',
    conference: 'ACC',
    state: 'GA',
    city: 'Atlanta',
    headCoach: 'Brent Key',
    oc: 'Chris Weinke',
    dc: 'D.J. Crook',
    recruitingCoord: 'Lamar Owens',
    staffPage: 'https://ramblinwreck.com/sports/football/roster/coaches',
        contactEmail: 'gtfbrecruiting@athletics.gatech.edu',
    contactPhone: '(404) 894-5411',
    mailingAddress: 'GT Football, 150 Bobby Dodd Way NW, Atlanta, GA 30332',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachBrentKey',
    hcInstagram: '',
    rcTwitter: 'CoachLamarOwens',
    rcInstagram: '',
    espnId: 59,
  },
  {
    school: 'University of North Carolina',
    domain: 'unc.edu',
    nickname: 'Tar Heels',
    division: 'FBS',
    conference: 'ACC',
    state: 'NC',
    city: 'Chapel Hill',
    headCoach: 'Bill Belichick',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://goheels.com/sports/football/roster/coaches',
        contactEmail: 'fbrecruiting@unc.edu',
    contactPhone: '(919) 962-2123',
    mailingAddress: 'UNC Football, P.O. Box 2126, Chapel Hill, NC 27515',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachBelichick',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 153,
  },
  {
    school: 'NC State University',
    domain: 'ncsu.edu',
    nickname: 'Wolfpack',
    division: 'FBS',
    conference: 'ACC',
    state: 'NC',
    city: 'Raleigh',
    headCoach: 'Dave Doeren',
    oc: 'Robert Anae',
    dc: 'Tony Gibson',
    recruitingCoord: 'Tre Thompson',
    staffPage: 'https://gopack.com/sports/football/roster/coaches',
        contactEmail: 'ncstatefootball@ncsu.edu',
    contactPhone: '(919) 515-2101',
    mailingAddress: 'NCSU Football, P.O. Box 8501, Raleigh, NC 27695',
    lastUpdated: '2026-04'
    espnId: 152,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

  // ============================================
  // FBS — Big Ten
  // ============================================
  {
    school: 'University of Michigan',
    domain: 'umich.edu',
    nickname: 'Wolverines',
    division: 'FBS',
    conference: 'Big Ten',
    state: 'MI',
    city: 'Ann Arbor',
    headCoach: 'Sherrone Moore',
    oc: 'Kirk Campbell',
    dc: 'Wink Martindale',
    recruitingCoord: 'Steve Clinkscale',
    staffPage: 'https://mgoblue.com/sports/football/roster/coaches',
        contactEmail: 'footballrecruiting@umich.edu',
    contactPhone: '(734) 763-4423',
    mailingAddress: 'UM Football, 1201 S Main St, Ann Arbor, MI 48104',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachSherrone',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 130,
  },
  {
    school: 'Ohio State University',
    domain: 'osu.edu',
    nickname: 'Buckeyes',
    division: 'FBS',
    conference: 'Big Ten',
    state: 'OH',
    city: 'Columbus',
    headCoach: 'Ryan Day',
    oc: 'Chip Kelly',
    dc: 'Jim Knowles',
    recruitingCoord: 'Brian Hartline',
    staffPage: 'https://ohiostatebuckeyes.com/sports/football/roster/coaches',
        contactEmail: 'football@osu.edu',
    contactPhone: '(614) 292-6861',
    mailingAddress: 'OSU Football, Woody Hayes Athletic Ctr, Columbus, OH 43210',
    lastUpdated: '2026-04',
    hcTwitter: 'ryandayfootball',
    hcInstagram: 'ryandayfootball',
    rcTwitter: 'brianhartline',
    rcInstagram: 'brianhartline',
    espnId: 194,
  },
  {
    school: 'Penn State University',
    domain: 'psu.edu',
    nickname: 'Nittany Lions',
    division: 'FBS',
    conference: 'Big Ten',
    state: 'PA',
    city: 'State College',
    headCoach: 'James Franklin',
    oc: 'Andy Kotelnicki',
    dc: 'Tom Allen',
    recruitingCoord: 'Ja\'Juan Seider',
    staffPage: 'https://gopsusports.com/sports/football/roster/coaches',
        contactEmail: 'fbrecruiting@psu.edu',
    contactPhone: '(814) 865-1000',
    mailingAddress: 'PSU Football, Lasch Football Building, University Park, PA 16802',
    lastUpdated: '2026-04',
    hcTwitter: 'coachjfranklin',
    hcInstagram: 'jamesfranklin22',
    rcTwitter: 'JaJuanSeider',
    rcInstagram: '',
    espnId: 213,
  },
  {
    school: 'USC',
    domain: 'usc.edu',
    nickname: 'Trojans',
    division: 'FBS',
    conference: 'Big Ten',
    state: 'CA',
    city: 'Los Angeles',
    headCoach: 'Lincoln Riley',
    oc: 'Luke Huard',
    dc: 'D\'Anton Lynn',
    recruitingCoord: 'Donte Williams',
    staffPage: 'https://usctrojans.com/sports/football/roster/coaches',
        contactEmail: 'footballrecruiting@usc.edu',
    contactPhone: '(213) 740-4155',
    mailingAddress: 'USC Football, Heritage Hall, Los Angeles, CA 90089',
    lastUpdated: '2026-04',
    hcTwitter: 'LincolnRiley',
    hcInstagram: 'lincolnriley',
    rcTwitter: 'donte_williams3',
    rcInstagram: '',
    espnId: 30,
  },
  {
    school: 'UCLA',
    domain: 'ucla.edu',
    nickname: 'Bruins',
    division: 'FBS',
    conference: 'Big Ten',
    state: 'CA',
    city: 'Los Angeles',
    headCoach: 'DeShaun Foster',
    oc: 'Eric Bieniemy',
    dc: 'Jake Dickert',
    recruitingCoord: 'Brian Norwood',
    staffPage: 'https://uclabruins.com/sports/football/roster/coaches',
        contactEmail: 'football@athletics.ucla.edu',
    contactPhone: '(310) 825-3321',
    mailingAddress: 'UCLA Football, P.O. Box 24044, Los Angeles, CA 90024',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachDeShaunF',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 26,
  },

  // ============================================
  // FBS — Big 12
  // ============================================
  {
    school: 'University of Oklahoma',
    domain: 'ou.edu',
    nickname: 'Sooners',
    division: 'FBS',
    conference: 'SEC',
    state: 'OK',
    city: 'Norman',
    headCoach: 'Brent Venables',
    oc: 'Seth Littrell',
    dc: 'Todd Bates',
    recruitingCoord: 'DeMarco Murray',
    staffPage: 'https://soonersports.com/sports/football/roster/coaches',
        contactEmail: 'football@ou.edu',
    contactPhone: '(405) 325-2345',
    mailingAddress: 'OU Athletics, McClendon Center, 180 W Brooks, Norman, OK 73019',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachVenables',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 201,
  },
  {
    school: 'TCU',
    domain: 'tcu.edu',
    nickname: 'Horned Frogs',
    division: 'FBS',
    conference: 'Big 12',
    state: 'TX',
    city: 'Fort Worth',
    headCoach: 'Sonny Dykes',
    oc: 'Kendal Briles',
    dc: 'Dennis Simmons',
    recruitingCoord: 'Tre Richardson',
    staffPage: 'https://gofrogs.com/sports/football/roster/coaches',
        contactEmail: 'football@tcu.edu',
    contactPhone: '(817) 257-7965',
    mailingAddress: 'TCU Football, P.O. Box 297600, Fort Worth, TX 76129',
    lastUpdated: '2026-04',
    hcTwitter: 'SonnyDykes',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 2628,
  },
  {
    school: 'Baylor University',
    domain: 'baylor.edu',
    nickname: 'Bears',
    division: 'FBS',
    conference: 'Big 12',
    state: 'TX',
    city: 'Waco',
    headCoach: 'Dave Aranda',
    oc: 'Jake Spavital',
    dc: 'Ron Roberts',
    recruitingCoord: 'Terrel Bernard',
    staffPage: 'https://baylorbears.com/sports/football/roster/coaches',
        contactEmail: 'football@baylor.edu',
    contactPhone: '(254) 710-1234',
    mailingAddress: 'Baylor Football, One Bear Place, Waco, TX 76798',
    lastUpdated: '2026-04',
    hcTwitter: 'CoachDaveAranda',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',
    espnId: 239,
  },
  {
    school: 'University of Houston',
    domain: 'uh.edu',
    nickname: 'Cougars',
    division: 'FBS',
    conference: 'Big 12',
    state: 'TX',
    city: 'Houston',
    headCoach: 'Willie Fritz',
    oc: 'TBD',
    dc: 'Doug Belk',
    recruitingCoord: 'TBD',
    staffPage: 'https://uhcougars.com/sports/football/roster/coaches',
        contactEmail: 'footballrecruiting@uh.edu',
    contactPhone: '(832) 842-6900',
    mailingAddress: 'UH Football, 3204 Cullen Blvd, Houston, TX 77204',
    lastUpdated: '2026-04'
    espnId: 248,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

  // ============================================
  // FCS — Top Programs
  // ============================================
  {
    school: 'Georgia Southern University',
    domain: 'georgiasouthern.edu',
    nickname: 'Eagles',
    division: 'FCS',
    conference: 'Sun Belt',
    state: 'GA',
    city: 'Statesboro',
    headCoach: 'Clay Helton',
    oc: 'Bryan Ellis',
    dc: 'Scot Sloan',
    recruitingCoord: 'Marcus Satterfield',
    staffPage: 'https://gseagles.com/sports/football/roster/coaches',
        contactEmail: 'fbrecruiting@georgiasouthern.edu',
    contactPhone: '(912) 478-5436',
    mailingAddress: 'GSU Football, P.O. Box 8082, Statesboro, GA 30460',
    lastUpdated: '2026-04'
    espnId: 290,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Kennesaw State University',
    domain: 'kennesaw.edu',
    nickname: 'Owls',
    division: 'FCS',
    conference: 'ASUN',
    state: 'GA',
    city: 'Kennesaw',
    headCoach: 'Brian Bohannon',
    oc: 'Taylor Lamb',
    dc: 'Erin Henderson',
    recruitingCoord: 'Carlos White',
    staffPage: 'https://ksuowls.com/sports/football/roster/coaches',
        contactEmail: 'ksufootball@kennesaw.edu',
    contactPhone: '(470) 578-6300',
    mailingAddress: 'KSU Football, 590 Cobb Ave NW, Kennesaw, GA 30144',
    lastUpdated: '2026-04'
    espnId: 2391,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Jackson State University',
    domain: 'jsums.edu',
    nickname: 'Tigers',
    division: 'FCS',
    conference: 'SWAC',
    state: 'MS',
    city: 'Jackson',
    headCoach: 'TC Taylor',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://gojagsports.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 2344,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'North Dakota State University',
    domain: 'ndsu.edu',
    nickname: 'Bison',
    division: 'FCS',
    conference: 'Missouri Valley',
    state: 'ND',
    city: 'Fargo',
    headCoach: 'Matt Entz',
    oc: 'Tim Polasek',
    dc: 'Randy Hedberg',
    recruitingCoord: 'Andrew Herbst',
    staffPage: 'https://gobison.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 2449,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'South Dakota State University',
    domain: 'sdstate.edu',
    nickname: 'Jackrabbits',
    division: 'FCS',
    conference: 'Missouri Valley',
    state: 'SD',
    city: 'Brookings',
    headCoach: 'Jimmy Rogers',
    oc: 'Zach Lujan',
    dc: 'Paul Troth',
    recruitingCoord: 'Dan Kroger',
    staffPage: 'https://gojacks.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 2571,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'University of Montana',
    domain: 'umt.edu',
    nickname: 'Grizzlies',
    division: 'FCS',
    conference: 'Big Sky',
    state: 'MT',
    city: 'Missoula',
    headCoach: 'Bobby Hauck',
    oc: 'Timm Rosenbach',
    dc: 'Kent Baer',
    recruitingCoord: 'Joe Hauck',
    staffPage: 'https://gogriz.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 149,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Villanova University',
    domain: 'villanova.edu',
    nickname: 'Wildcats',
    division: 'FCS',
    conference: 'CAA',
    state: 'PA',
    city: 'Villanova',
    headCoach: 'Mark Ferrante',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://villanova.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 222,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'James Madison University',
    domain: 'jmu.edu',
    nickname: 'Dukes',
    division: 'FBS',
    conference: 'Sun Belt',
    state: 'VA',
    city: 'Harrisonburg',
    headCoach: 'Bob Chesney',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://jmusports.com/sports/football/roster/coaches',
    lastUpdated: '2026-04'
    espnId: 256,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Bethune-Cookman University',
    domain: 'cookman.edu',
    nickname: 'Wildcats',
    division: 'FCS',
    conference: 'SWAC',
    state: 'FL',
    city: 'Daytona Beach',
    headCoach: 'Terry Sims',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://bcu.edu/athletics/football',
    lastUpdated: '2026-04'
    espnId: 2065,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Florida A&M University',
    domain: 'famu.edu',
    nickname: 'Rattlers',
    division: 'FCS',
    conference: 'SWAC',
    state: 'FL',
    city: 'Tallahassee',
    headCoach: 'James Colzie III',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://famuathletics.com/sports/football',
        contactEmail: 'football@famu.edu',
    contactPhone: '(850) 599-3200',
    mailingAddress: 'FAMU Football, 1800 Wahnish Way, Tallahassee, FL 32307',
    lastUpdated: '2026-04'
    espnId: 50,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

  // ============================================
  // Division II
  // ============================================
  {
    school: 'Valdosta State University',
    domain: 'valdosta.edu',
    nickname: 'Blazers',
    division: 'D2',
    conference: 'Gulf South',
    state: 'GA',
    city: 'Valdosta',
    headCoach: 'Gary Goff',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://valdostastateblazers.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2674,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Delta State University',
    domain: 'deltastate.edu',
    nickname: 'Statesmen',
    division: 'D2',
    conference: 'Gulf South',
    state: 'MS',
    city: 'Cleveland',
    headCoach: 'Todd Cooley',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://deltastateathletics.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Ferris State University',
    domain: 'ferris.edu',
    nickname: 'Bulldogs',
    division: 'D2',
    conference: 'GLIAC',
    state: 'MI',
    city: 'Big Rapids',
    headCoach: 'Tony Annese',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://ferrisstatebulldogs.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2209,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Pittsburg State University',
    domain: 'pittstate.edu',
    nickname: 'Gorillas',
    division: 'D2',
    conference: 'MIAA',
    state: 'KS',
    city: 'Pittsburg',
    headCoach: 'Tim Beck',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://pittgorillas.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'West Florida University',
    domain: 'uwf.edu',
    nickname: 'Argonauts',
    division: 'D2',
    conference: 'Gulf South',
    state: 'FL',
    city: 'Pensacola',
    headCoach: 'Kaleb Nobles',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://uwfargos.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2734,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Colorado School of Mines',
    domain: 'mines.edu',
    nickname: 'Orediggers',
    division: 'D2',
    conference: 'RMAC',
    state: 'CO',
    city: 'Golden',
    headCoach: 'Brandon Moore',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://minesathletics.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Tarleton State University',
    domain: 'tarleton.edu',
    nickname: 'Texans',
    division: 'D2',
    conference: 'Lone Star',
    state: 'TX',
    city: 'Stephenville',
    headCoach: 'Todd Whitten',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://tarletonsports.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2653,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Angelo State University',
    domain: 'angelo.edu',
    nickname: 'Rams',
    division: 'D2',
    conference: 'Lone Star',
    state: 'TX',
    city: 'San Angelo',
    headCoach: 'Jeff Girsch',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://angelosports.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2006,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

  // ============================================
  // Division III
  // ============================================
  {
    school: 'North Central College',
    domain: 'northcentralcollege.edu',
    nickname: 'Cardinals',
    division: 'D3',
    conference: 'CCIW',
    state: 'IL',
    city: 'Naperville',
    headCoach: 'Jeff Thorne',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://athletics.northcentralcollege.edu/sports/football',
    lastUpdated: '2026-04'
    espnId: 2461,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Mary Hardin-Baylor University',
    domain: 'umhb.edu',
    nickname: 'Crusaders',
    division: 'D3',
    conference: 'ASC',
    state: 'TX',
    city: 'Belton',
    headCoach: 'Pete Fredenburg',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://crusaders.umhb.edu/sports/football',
    lastUpdated: '2026-04'
    espnId: 2374,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Wartburg College',
    domain: 'wartburg.edu',
    nickname: 'Knights',
    division: 'D3',
    conference: 'ARC',
    state: 'IA',
    city: 'Waverly',
    headCoach: 'Mike Krzyzanowski',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://athletics.wartburg.edu/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Wheaton College',
    domain: 'wheaton.edu',
    nickname: 'Thunder',
    division: 'D3',
    conference: 'CCIW',
    state: 'IL',
    city: 'Wheaton',
    headCoach: 'Mike Swider',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://athletics.wheaton.edu/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Hardin-Simmons University',
    domain: 'hsutx.edu',
    nickname: 'Cowboys',
    division: 'D3',
    conference: 'ASC',
    state: 'TX',
    city: 'Abilene',
    headCoach: 'Jesse Burleson',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://hsucowboys.com/sports/football',
    lastUpdated: '2026-04'
    espnId: 2296,
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

  // ============================================
  // JUCO
  // ============================================
  {
    school: 'Georgia Military College',
    domain: 'gmc.cc.ga.us',
    nickname: 'Bulldogs',
    division: 'JUCO',
    conference: 'GCAA',
    state: 'GA',
    city: 'Milledgeville',
    headCoach: 'Pete Taylor',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://gmcbulldogs.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Georgia Northwestern Technical College',
    nickname: 'Cardinals',
    division: 'JUCO',
    conference: 'GCAA',
    state: 'GA',
    city: 'Rome',
    headCoach: 'TBD',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://gntc.edu/athletics',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Coffeyville Community College',
    domain: 'coffeyville.edu',
    nickname: 'Ravens',
    division: 'JUCO',
    conference: 'KJCCC',
    state: 'KS',
    city: 'Coffeyville',
    headCoach: 'Jason Brown',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://coffeyvilleravens.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Iowa Western Community College',
    domain: 'iwcc.edu',
    nickname: 'Reivers',
    division: 'JUCO',
    conference: 'ICCAC',
    state: 'IA',
    city: 'Council Bluffs',
    headCoach: 'Scott Strohmeier',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://iwccreivers.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Itawamba Community College',
    domain: 'iccms.edu',
    nickname: 'Indians',
    division: 'JUCO',
    conference: 'MACJC',
    state: 'MS',
    city: 'Fulton',
    headCoach: 'Chris Chamberlin',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://iccathletics.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Blinn College',
    domain: 'blinn.edu',
    nickname: 'Buccaneers',
    division: 'JUCO',
    conference: 'SWJCFC',
    state: 'TX',
    city: 'Brenham',
    headCoach: 'Scott Syma',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://blinnbuccaneers.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Northwest Mississippi Community College',
    domain: 'northwestms.edu',
    nickname: 'Rangers',
    division: 'JUCO',
    conference: 'MACJC',
    state: 'MS',
    city: 'Senatobia',
    headCoach: 'Benjy Landrum',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://northwestms.edu/athletics/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'East Mississippi Community College',
    domain: 'eastms.edu',
    nickname: 'Lions',
    division: 'JUCO',
    conference: 'MACJC',
    state: 'MS',
    city: 'Scooba',
    headCoach: 'Buddy Stephens',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://emcclions.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Snow College',
    domain: 'snow.edu',
    nickname: 'Badgers',
    division: 'JUCO',
    conference: 'SWAC',
    state: 'UT',
    city: 'Ephraim',
    headCoach: 'Paul Peterson',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://snowbadgers.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,
  {
    school: 'Garden City Community College',
    domain: 'gcccks.edu',
    nickname: 'Broncbusters',
    division: 'JUCO',
    conference: 'KJCCC',
    state: 'KS',
    city: 'Garden City',
    headCoach: 'Jeff Sims',
    oc: 'TBD',
    dc: 'TBD',
    recruitingCoord: 'TBD',
    staffPage: 'https://gcccbroncbusters.com/sports/football',
    lastUpdated: '2026-04'
  },
    hcTwitter: '',
    hcInstagram: '',
    rcTwitter: '',
    rcInstagram: '',,

];

// ============================================
// HELPER: get unique values for filters
// ============================================
const COACH_DIVISIONS  = [...new Set(COACHES_DATA.map(c => c.division))].sort();
const COACH_STATES     = [...new Set(COACHES_DATA.map(c => c.state))].sort();
const COACH_CONFERENCES = [...new Set(COACHES_DATA.map(c => c.conference))].sort();
